和tensor有关的笔记

# 产生tensor的各种方法

In [ ]:
import torch as t
import numpy as np

## 从numpy生成tensor

In [2]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = t.from_numpy(n)
print(x)
# n和x内部的数据是否使用相同的内存呢?
n[0][0] = 0
# 是的!
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[0, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## 定义空tensor 和随机数tensor

In [3]:
x = t.Tensor(3,2,4)

空tensor,没有初始化,值的范围很大.
随机数初始化后的tensor值的范围在0~1之间.
==要注意这两者的区别==

In [4]:
x

tensor([[[-1.1883e+16,  4.5748e-41, -2.7332e+29,  3.0911e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [-2.5289e+29,  3.0911e-41,  0.0000e+00,  0.0000e+00]],

        [[-2.7335e+29,  3.0911e-41, -2.7335e+29,  3.0911e-41],
         [-2.7335e+29,  3.0911e-41,  0.0000e+00,  0.0000e+00]]])

In [5]:
x = t.rand(3,2,4)

In [6]:
x

tensor([[[0.4425, 0.2156, 0.0283, 0.5273],
         [0.3865, 0.5311, 0.1423, 0.4639]],

        [[0.7096, 0.7792, 0.6286, 0.3830],
         [0.9422, 0.3639, 0.7237, 0.8913]],

        [[0.4050, 0.5139, 0.6028, 0.6433],
         [0.2190, 0.9309, 0.7384, 0.1902]]])

## 通过复制的方法生成tensor
- 浅拷贝: tensor底层的数据使用同一块内存,改变任意一个,其他的值都会变
- 深拷贝: tensor底层的数据使用独立内存,改变一个,其他的值不会变

In [7]:
# 使用=是浅拷贝
x2 = x
x[0][0][0] = 9
print(x2[0][0][0])

tensor(9.)


In [8]:
# 使用clone是深拷贝
x[0][0][0] = 1
x3 = x.clone()
x[0][0][0] = 8
print(x3[0][0][0])


tensor(1.)


In [9]:
# detatch返回使用同一片内存的tensor,
# 但是这个函数不是让你拷贝数据的,
# 而是让tensor从当前的计算图中脱离出来
help(x.detach)
x4=x.detach()
x[0][0][0] = 7
print(x4[0][0][0])

Help on built-in function detach:

detach(...) method of torch.Tensor instance
    Returns a new Tensor, detached from the current graph.
    
    The result will never require gradient.
    
    .. note::
    
      Returned Tensor shares the same storage with the original one.
      In-place modifications on either of them will be seen, and may trigger
      errors in correctness checks.
      IMPORTANT NOTE: Previously, in-place size / stride / storage changes
      (such as `resize_` / `resize_as_` / `set_` / `transpose_`) to the returned tensor
      also update the original tensor. Now, these in-place changes will not update the
      original tensor anymore, and will instead trigger an error.
      For sparse tensors:
      In-place indices / values changes (such as `zero_` / `copy_` / `add_`) to the
      returned tensor will not update the original tensor anymore, and will instead
      trigger an error.

tensor(7.)


# 从tensor转变成scaler
只有0维的tensor才可以转成scaler,否则会报错

In [45]:
import torch as t

In [46]:
# s 虽然只有1个数据,但是它依然是tensor
s = x[0][0]
print(s,s.shape)
type(s)

tensor(0.4388) torch.Size([])


torch.Tensor

In [47]:
# s1 是scaler
s1 = s.item()
print(s1)
type(s1)

0.43879348039627075


float

# tensor的数据类型
- t.uint8
- t.int16
- t.int8
- t.int32
- t.int64
- t.int = t.int32
- t.float16
- t.float32
- t.float64
- t.float = t.float32
- t.double = t.float64

In [48]:
import torch as t

In [49]:
t.float

torch.float32

In [50]:
t.double

torch.float64

In [51]:
t.int

torch.int32

In [52]:
t.uint8

torch.uint8

# 在CPU还是在GPU上

In [53]:
import torch as t

In [54]:
# 首先创建一个CPU或者GPU的device,然后用tensor.to把tensor转移到device上
device = t.device("cuda:0" if t.cuda.is_available() else "cpu")

In [55]:
x = t.rand(5,3)
print(x,x.device)

tensor([[0.4106, 0.6737, 0.0043],
        [0.7891, 0.4465, 0.0342],
        [0.3430, 0.2912, 0.7660],
        [0.0554, 0.4707, 0.2168],
        [0.0857, 0.7483, 0.0282]]) cpu


In [56]:
x = x.to(device)

In [57]:
print(x,x.device)

tensor([[0.4106, 0.6737, 0.0043],
        [0.7891, 0.4465, 0.0342],
        [0.3430, 0.2912, 0.7660],
        [0.0554, 0.4707, 0.2168],
        [0.0857, 0.7483, 0.0282]], device='cuda:0') cuda:0


## to ()

to(,dtype=None) 默认情况下dtype是None,保持数据格式不变

In [58]:
help(x.to)

Help on built-in function to:

to(...) method of torch.Tensor instance
    to(*args, **kwargs) -> Tensor
    
    Performs Tensor dtype and/or device conversion. A :class:`torch.dtype` and :class:`torch.device` are
    inferred from the arguments of ``self.to(*args, **kwargs)``.
    
    .. note::
    
        If the ``self`` Tensor already
        has the correct :class:`torch.dtype` and :class:`torch.device`, then ``self`` is returned.
        Otherwise, the returned tensor is a copy of ``self`` with the desired
        :class:`torch.dtype` and :class:`torch.device`.
    
    Here are the ways to call ``to``:
    
    .. function:: to(dtype, non_blocking=False, copy=False, memory_format=torch.preserve_format) -> Tensor
    
        Returns a Tensor with the specified :attr:`dtype`
    
        Args:
            memory_format (:class:`torch.memory_format`, optional): the desired memory format of
            returned Tensor. Default: ``torch.preserve_format``.
    
    .. function:: to